use_frameworks!

platform :ios, '15.0'

target 'NovaSdk_Example' do
  pod 'NovaSdk', :path => '../'

  pod 'Adjust', '~> 5.5.1'
  pod 'MMKV'
  pod 'SnapKit'
  pod 'MBProgressHUD'

  pod 'Firebase'

  target 'NovaSdk_Tests' do
    inherit! :search_paths


  end
end
