#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef AHSDK_SWIFT_H
#define AHSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AHSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Represents the user’s tracking status
typedef SWIFT_ENUM(NSUInteger, AdvertisingTrackingStatus, open) {
  AdvertisingTrackingStatusAllowed = 0,
  AdvertisingTrackingStatusDisallowed = 1,
  AdvertisingTrackingStatusUnspecified = 2,
};

/// Represents the valid user data types for advanced matching
typedef SWIFT_ENUM(NSInteger, AppEventUserDataType, open) {
  AppEventUserDataTypeEmail = 0,
  AppEventUserDataTypeFirstName = 1,
  AppEventUserDataTypeLastName = 2,
  AppEventUserDataTypePhone = 3,
  AppEventUserDataTypeDateofBirth = 4,
  AppEventUserDataTypeGender = 5,
  AppEventUserDataTypeCity = 6,
  AppEventUserDataTypeState = 7,
  AppEventUserDataTypeZip = 8,
  AppEventUserDataTypeCountry = 9,
  AppEventUserDataTypeExternalId = 10,
};

@class NSString;
enum AHSDKEventName : NSInteger;
SWIFT_CLASS_NAMED("AppEvents")
@interface AHSDKAppEvents : NSObject
/// The shared instance of AppEvents.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AHSDKAppEvents * _Nonnull sharedInstance;)
+ (AHSDKAppEvents * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Logs an event with a specific name to the Gateway, optionally including a unique identifier (eventId) for deduplication and additional parameters for enhanced context.
/// \param eventName A required string that describes the event. The name appears in the Event log when the app event is sent to Gateway
///
/// \param eventId An optional unique identifier for the event, aiding in deduplication
///
/// \param parameters An optional dictionary of additional data (key-value pairs) to be included with the event, providing richer context. Both keys and values must be serializable. The keys to this dictionary must be <code>String</code>s, and the values are expected to be strings or numbers.
///
- (void)logEvent:(NSString * _Nonnull)eventName eventId:(NSString * _Nullable)eventId parameters:(NSDictionary<NSString *, id> * _Nullable)parameters;
/// Logs an event with a specific name to the Gateway, optionally including a unique identifier (eventId) for deduplication and additional parameters for enhanced context.
/// \param eventName A standard value of the EventName enumeration that describes the event. The name appears in the Event log when the app event is sent to Gateway
///
/// \param eventId An optional unique identifier for the event, aiding in deduplication
///
/// \param parameters An optional dictionary of additional data (key-value pairs) to be included with the event, providing richer context. Both keys and values must be serializable. The keys to this dictionary must be <code>String</code>s, and the values are expected to be strings or numbers.
///
- (void)logEventWithStandardEventName:(enum AHSDKEventName)eventName eventId:(NSString * _Nullable)eventId parameters:(NSDictionary<NSString *, id> * _Nullable)parameters;
/// Logs an event with a specified name and a numeric value, which is aggregated with other events of the same name, to the Gateway. It optionally includes a unique identifier (eventId) for deduplication and additional parameters for enhanced context.
/// \param eventName A required string that describes the event. The name appears in the Event log when the app event is sent to Gateway
///
/// \param valueToSum A  value that Analytics adds to other Value To Sum values from app events with the same name.
///
/// \param eventId An optional unique identifier for the event, aiding in deduplication
///
/// \param parameters An optional dictionary of additional data (key-value pairs) to be included with the event, providing richer context. Both keys and values must be serializable. The keys to this dictionary must be <code>String</code>s, and the values are expected to be strings or numbers.
///
- (void)logEvent:(NSString * _Nonnull)eventName valueToSum:(double)valueToSum eventId:(NSString * _Nullable)eventId parameters:(NSDictionary<NSString *, id> * _Nullable)parameters;
/// Logs an event with a specified name and a numeric value, which is aggregated with other events of the same name, to the Gateway. It optionally includes a unique identifier (eventId) for deduplication and additional parameters for enhanced context.
/// \param eventName A standard value of the EventName enumeration that describes the event. The name appears in the Event log when the app event is sent to Gateway
///
/// \param valueToSum A  value that Analytics adds to other Value To Sum values from app events with the same name.
///
/// \param eventId An optional unique identifier for the event, aiding in deduplication
///
/// \param parameters An optional dictionary of additional data (key-value pairs) to be included with the event, providing richer context. Both keys and values must be serializable. The keys to this dictionary must be <code>String</code>s, and the values are expected to be strings or numbers.
///
- (void)logEventWithStandardEventName:(enum AHSDKEventName)eventName valueToSum:(double)valueToSum eventId:(NSString * _Nullable)eventId parameters:(NSDictionary<NSString *, id> * _Nullable)parameters;
/// Logs a purchase event with the specified amount and currency to the Gateway. Optionally, it includes a unique identifier (eventId) for deduplication and additional parameters for enhanced context.
/// note:
/// Triggering this event causes an immediate flush of the <code>AppEvents</code> event queue, ensuring timely processing.
/// \param purchaseAmount Purchase amount to be logged, as expressed in the specified currency.  This value will be rounded to the thousandths place (e.g., 12.34567 becomes 12.346).
///
/// \param currency Currency string (e.g., “USD”, “EUR”, “GBP”); see ISO-4217 for specific values.  One reference for these is <a href="http://en.wikipedia.org/wiki/ISO_4217">http://en.wikipedia.org/wiki/ISO_4217</a>.
///
/// \param eventId An optional unique identifier for the event, aiding in deduplication
///
/// \param parameters An optional dictionary of additional data (key-value pairs) to be included with the event, providing richer context. Both keys and values must be serializable. The keys to this dictionary must be <code>String</code>s, and the values are expected to be strings or numbers.
///
- (void)logPurchaseWithPurchaseAmount:(double)purchaseAmount currency:(NSString * _Nonnull)currency eventId:(NSString * _Nullable)eventId parameters:(NSDictionary<NSString *, id> * _Nullable)parameters;
/// Logs a failed StoreKit V2 purchase event to the Gateway. Optionally, it includes a unique identifier (eventId) for deduplication and additional parameters for enhanced context.
/// note:
/// This API is only used for StoreKit V2 logging <a href="https://developer.apple.com/documentation/storekit/in-app-purchase">https://developer.apple.com/documentation/storekit/in-app-purchase</a>,  Not for StoreKit V1<a href="https://developer.apple.com/documentation/storekit/original-api-for-in-app-purchase">https://developer.apple.com/documentation/storekit/original-api-for-in-app-purchase</a>
/// \param productID The product Identifier for the failed purchase defined at the storekit file or apple store connect.
///
/// \param eventId An optional unique identifier for the event, aiding in deduplication
///
/// \param parameters An optional dictionary of additional data (key-value pairs) to be included with the event, providing richer context. Both keys and values must be serializable. The keys to this dictionary must be <code>String</code>s, and the values are expected to be strings or numbers.
///
- (void)logFailedStoreKit2PurchaseWithProductID:(NSString * _Nonnull)productID eventId:(NSString * _Nullable)eventId parameters:(NSDictionary<NSString *, id> * _Nullable)parameters;
/// Explicitly kick off flushing of events.  This is an asynchronous method, but it does initiate an immediate kick off.
- (void)flush;
/// Sets custom user data to associate with all app events. All user data are hashed
/// and used to match users from this instance of an application.
/// The user data will be persisted between application instances.
/// \param email email user’s email
///
/// \param firstName user’s first name
///
/// \param lastName user’s last name 
///
/// \param phone user’s phone 
///
/// \param dateOfBirth user’s date of birth 
///
/// \param gender user’s gender 
///
/// \param city user’s city 
///
/// \param state user’s state 
///
/// \param zip user’s zip 
///
/// \param country user’s country 
///
/// \param externalId user’s unique ID from the advertiser, such as loyalty membership IDs and user IDs 
///
- (void)setUserEmail:(NSString * _Nullable)email firstName:(NSString * _Nullable)firstName lastName:(NSString * _Nullable)lastName phone:(NSString * _Nullable)phone dateOfBirth:(NSString * _Nullable)dateOfBirth gender:(NSString * _Nullable)gender city:(NSString * _Nullable)city state:(NSString * _Nullable)state zip:(NSString * _Nullable)zip country:(NSString * _Nullable)country externalId:(NSString * _Nullable)externalId;
/// Returns the set user data else nil
- (NSString * _Nullable)getUserData SWIFT_WARN_UNUSED_RESULT;
/// Sets custom user data to associate with all app events. All user data are hashed.
/// The user data will be persisted between application instances.
/// \param data user data
///
/// \param type data type (should correspond to one of the options in the AppEventUserDataType enum)
///
- (void)setUserData:(NSString * _Nullable)data forType:(NSString * _Nonnull)type;
/// Sets custom user data to associate with all app events. All user data are hashed.
/// The user data will be persisted between application instances.
/// \param data user data
///
/// \param type data type
///
- (void)setUserData:(NSString * _Nullable)data forUserDataType:(enum AppEventUserDataType)type;
/// Clears the current user data
- (void)clearUserData;
/// Clears the current user data of certain type
/// \param type data type (should correspond to one of the options in the AppEventUserDataType enum)
///
- (void)clearUserDataForType:(NSString * _Nonnull)type;
/// Clears the current user data of certain type
/// \param type data type
///
- (void)clearUserDataForTypeWithUserDataType:(enum AppEventUserDataType)type;
@end

@class UIApplication;
@class NSUserActivity;
@class NSURL;
SWIFT_CLASS_NAMED("ApplicationDelegate")
@interface AHSDKApplicationDelegate : NSObject
/// Gets the singleton instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AHSDKApplicationDelegate * _Nonnull sharedInstance;)
+ (AHSDKApplicationDelegate * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull minSupportedOSVersion;)
+ (NSString * _Nonnull)minSupportedOSVersion SWIFT_WARN_UNUSED_RESULT;
/// Initializes the SDK.
/// <ul>
///   <li>
///     Note If you are using the SDK within the context of the <code>UIApplication</code> lifecycle, do not use this method.
///     Instead use <code>application(_:didFinishLaunchingWithOptions:)</code>.
///     As part of SDK initialization, basic auto logging of app events will occur, this can be
///     controlled via the ‘AutoLogAppEventsEnabled’ key in your project’s Info.plist file.
///   </li>
/// </ul>
///
/// returns:
/// <code>false</code> if the OS version is lower than SDK’s  minimum supported version
- (BOOL)initializeSDK;
/// Call this method from the <code>UIApplicationDelegate.application(_:didFinishLaunchingWithOptions:)</code> method
/// of your application delegate.
/// As part of SDK initialization, basic auto-logging of app events will occur.
/// Tthis can be controlled via the <code>AutoLogAppEventsEnabled</code> key in the project’s Info.plist file.
/// \param application The application as passed to <code>UIApplicationDelegate.application(_:didFinishLaunchingWithOptions:)</code>.
///
/// \param launchOptions The launch options as passed to <code>UIApplicationDelegate.application(_:didFinishLaunchingWithOptions:)</code>.
///
///
/// returns:
/// <code>true</code> if there are any added application observers that themselves return true from calling <code>application(_:didFinishLaunchingWithOptions:)</code>.
/// Otherwise will return <code>false</code>.
/// If this method is called after calling <code>initializeSDK</code>, then the return value will always be <code>false</code>.
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions;
/// Call this method from the <code>UIApplicationDelegate.application(_:continue:restorationHandler:) method</code>
/// of your application delegate.
/// It should be invoked in order to properly process the web URL (universal link)
/// once the end user is redirected to your app.
/// \param application The application as passed to `UIApplicationDelegate.application(_:continue:restorationHandler:).
///
/// \param userActivity The user activity as passed to UIApplicationDelegate.application(_:continue:restorationHandler:).
///
///
/// returns:
/// true if the URL was intended for the SDK, false if not.
- (BOOL)application:(UIApplication * _Nonnull)application continueUserActivity:(NSUserActivity * _Nonnull)userActivity;
/// Call this method from the <code>UIApplicationDelegate.application(_:open:options:)</code> method
/// of your application delegate.
/// It should be invoked for the proper processing of responses during interaction
/// with the native app or Safari as part of an SSO authorization flow or dialogs.
/// \param application The application as passed to <code>UIApplicationDelegate.application(_:open:options:)</code>.
///
/// \param url The URL as passed to <code>UIApplicationDelegate.application(_:open:options:)</code>.
///
/// \param options The options dictionary as passed to <code>UIApplicationDelegate.application(_:open:options:)</code>.
///
///
/// returns:
/// <code>true</code> if the URL was intended for the SDK, <code>false</code> if not.
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options;
/// Call this method from the <code>UIApplicationDelegate.application(_:open:sourceApplication:annotation:)</code> method
/// of your application delegate.
/// It should be invoked for the proper processing of responses during interaction
/// with the native app or Safari as part of an SSO authorization flow or dialogs.
/// \param application The application as passed to <code>UIApplicationDelegate.application(_:open:sourceApplication:annotation:)</code>.
///
/// \param url The URL as passed to <code>UIApplicationDelegate.application(_:open:sourceApplication:annotation:)</code>.
///
/// \param sourceApplication The source application as passed to <code>UIApplicationDelegate.application(_:open:sourceApplication:annotation:)</code>.
///
/// \param annotation The annotation as passed to <code>UIApplicationDelegate.application(_:open:sourceApplication:annotation:)</code>.
///
///
/// returns:
/// <code>true</code> if the URL was intended for the SDK, <code>false</code> if not.
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nullable)annotation;
@end

/// Represents the standard event names for app events
typedef SWIFT_ENUM_NAMED(NSInteger, AHSDKEventName, "EventName", open) {
/// When a person clicks on an ad,
/// i.e., a person clicks on an interstitial ad.
  AHSDKEventNameAdClick = 0,
/// When an ad is presented on a person’s screen,
/// i.e., when playing a video game, the user is shown an ad between levels.
  AHSDKEventNameAdImpression = 1,
/// When a person initiates contact with your business,
/// i.e., a person submits a question about a product.
  AHSDKEventNameContact = 2,
/// When a person customizes a product,
/// i.e., a person selects the color of a t-shirt.
  AHSDKEventNameCustomizeProduct = 3,
/// When a person donates funds to your organization or cause,
/// i.e., a person adds a donation to the Humane Society to their cart.
  AHSDKEventNameDonate = 4,
/// When a person searches for a location of your store via a website or app, with an intention to visit the physical location,
/// i.e., a person wants to find a specific product in a local store.
  AHSDKEventNameFindLocation = 5,
/// When a person rates a product or service you offer,
/// i.e., a person gives a rating to a movie on a streaming platform.
  AHSDKEventNameRate = 6,
/// When a person books an appointment to visit one of your locations,
/// i.e., a person selects a date and time for a tennis lesson.
  AHSDKEventNameSchedule = 7,
/// When a search is made,
/// i.e., a person searches for a product on your website.
  AHSDKEventNameSearch = 8,
/// When a person starts a free trial of a product or service you offer,
/// i.e., a person selects a free week of your game.
  AHSDKEventNameStartTrial = 9,
/// When a person applies for a product, service, or program you offer,
/// i.e., a person applies for a credit card, educational program, or job.
  AHSDKEventNameSubmitApplication = 10,
/// When a person applies to start a paid subscription for a product or service you offer,
/// i.e., a person subscribes to your streaming service.
  AHSDKEventNameSubscribe = 11,
/// When a person opens or launches your application,
/// i.e., a user taps the icon to open your mobile game.
  AHSDKEventNameActivateApp = 12,
/// When payment information is added in the checkout flow,
/// i.e., a person clicks on a save billing information button.
  AHSDKEventNameAddPaymentInfo = 13,
/// When a product is added to the shopping cart,
/// i.e., a person clicks on an add to cart button.
  AHSDKEventNameAddToCart = 14,
/// When a product is added to a wishlist,
/// i.e., a person clicks on an add to wishlist button.
  AHSDKEventNameAddToWishlist = 15,
/// When a person enters the checkout flow prior to completing the checkout flow,
/// i.e., a person clicks on a checkout button.
  AHSDKEventNameInitiateCheckout = 16,
/// When a purchase is made or checkout flow is completed,
/// i.e., a person has finished the purchase or checkout flow and lands on thank you or confirmation page.
  AHSDKEventNamePurchase = 17,
/// When a purchase fails to complete due to various reasons such as payment issues or technical problems,
/// i.e., a person attempts to buy an item but the transaction fails because of insufficient funds in their account.
  AHSDKEventNamePurchaseFailed = 18,
/// When a previously failed purchase is successfully restored through recovery mechanisms like auto-restore or user retry,
/// i.e., after initially failing to buy an item due to a temporary issue, the customer retries and completes the purchase.
  AHSDKEventNamePurchaseRestored = 19,
/// When a person initiates the checkout process for a subscription-based product or service you offer,
/// i.e., a person starts the sign-up process for your streaming service with a monthly subscription plan.
  AHSDKEventNameSubscriptionInitiatedCheckout = 20,
/// When a subscription fails due to payment issues, cancellation, or other reasons,
/// i.e., a subscriber’s monthly payment for your streaming service cannot be processed due to a card error.
  AHSDKEventNameSubscriptionFailed = 21,
/// When a previously failed or canceled subscription is successfully restored through recovery mechanisms like auto-restore or user retry,
/// i.e., after resolving the initial payment issue, a subscriber’s monthly subscription is reactivated.
  AHSDKEventNameSubscriptionRestored = 22,
/// When a person reaches a new level in your application, game, or service,
/// i.e., a player reaches level 10 in your mobile game.
  AHSDKEventNameLevelAchieved = 23,
/// When a person unlocks an achievement within your application, game, or service,
/// i.e., a player unlocks the “First Win” achievement in your game.
  AHSDKEventNameAchievementUnlocked = 24,
/// When a person spends credits or virtual currency within your application, game, or service,
/// i.e., a player buys a special item using the in-game currency.
  AHSDKEventNameSpendCredits = 25,
/// When a registration form is completed,
/// i,e. a person submits a completed subscription or signup form.
  AHSDKEventNameCompleteRegistration = 26,
/// When a sign up is completed,
/// i.e., a person clicks on pricing.
  AHSDKEventNameLead = 27,
/// A visit to a page you care about (for example, a product page or landing page),
/// i.e., a person lands on a product details page.
  AHSDKEventNameViewContent = 28,
};

/// Serves as a centralized location for managing various settings and configurations related to the SDK
SWIFT_CLASS_NAMED("Settings")
@interface AHSDKSettings : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The shared settings instance. Prefer this and the exposed instance methods over the type properties and methods.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AHSDKSettings * _Nonnull sharedSettings;)
+ (AHSDKSettings * _Nonnull)sharedSettings SWIFT_WARN_UNUSED_RESULT;
/// The SDK version in use.
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
/// Controls the automatic logging of basic app events such as <code>activateApp</code> and <code>deactivateApp</code>.
/// default value is <code>true</code>.
@property (nonatomic) BOOL isAutoLogAppEventsEnabled;
/// Controls the access to IDFA.
/// default value is <code>true</code>.
@property (nonatomic) BOOL isAdvertiserIDCollectionEnabled;
/// Whether data such as that generated through <code>AppEvents</code> and sent to server
/// should be restricted from being used for purposes other than analytics and conversions.
/// default value is <code>false</code>. This value is stored on the device and persists across app launches.
@property (nonatomic) BOOL isEventDataUsageLimited;
/// The Gateway data source ID used by the SDK.
/// The default value will be read from the application’s plist (GatewayDataSourceID).
@property (nonatomic, readonly, copy) NSString * _Nullable dataSourceID;
/// The Gateway domain used by the SDK.
/// The default value will be read from the application’s plist (GatewayDomain).
@property (nonatomic, readonly, copy) NSString * _Nullable domain;
/// Use the Advertiser Tracking Enabled parameter to indicate whether the SDK should use event data for tracking.
/// The default value is <code>false</code>.
@property (nonatomic) BOOL isAdvertiserTrackingEnabled;
/// Set the data processing options.
/// <ul>
///   <li>
///     Example:
///     <ul>
///       <li>
///         To explicitly not enable LDU, use:
///         Settings.shared.setDataProcessingOptions(modes: [])
///       </li>
///       <li>
///         To enable LDU and have default perform geolocation, use:
///         Settings.shared.setDataProcessingOptions(modes: [“LDU”])
///       </li>
///     </ul>
///   </li>
/// </ul>
/// \param options Processing options you would like to enable for a specific event. Current accepted value is LDU for Limited Data Use. An empty array can be sent to explicitly specify that this event shouldn’t be processed with the Limited Data Use restrictions.
///
- (void)setDataProcessingOptions:(NSArray<NSString *> * _Nullable)options;
/// Sets the data processing options.
/// note:
/// If you set a country, you must also set a state. Otherwise, we apply our geolocation logic to the entire event. This field is required if you send LDU under data_processing_options and do not provide an IP address.
/// <ul>
///   <li>
///     Example:
///     <ul>
///       <li>
///         To explicitly not enable LDU, use:
///         Settings.shared.setDataProcessingOptions(modes: [])
///       </li>
///       <li>
///         To enable LDU and have geolocation, use:
///         Settings.shared.setDataProcessingOptions(modes: [“LDU”], country: 0, state: 0)
///       </li>
///       <li>
///         To enable LDU and manually specify the location, e.g., for California, use:
///         Settings.shared.setDataProcessingOptions(modes: [“LDU”], country: 1, state: 1000)
///       </li>
///     </ul>
///   </li>
/// </ul>
/// \param options Processing options you would like to enable for a specific event. Current accepted value is LDU for Limited Data Use. An empty array can be sent to explicitly specify that this event shouldn’t be processed with the Limited Data Use restrictions.
///
/// \param country Required, if you pass LDU to <code>options</code>. A country that you want to associate to this data processing option. Current accepted values are 1, for the United States of America, or 0.
///
/// \param state Required in some cases. (See note below for details.) A state that you want to associate to this data processing option. Current accepted values are 1000, for California, or 0.
///
- (void)setDataProcessingOptions:(NSArray<NSString *> * _Nullable)options country:(NSInteger)country state:(NSInteger)state;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
